### ISSUE TITLE
I´m new to this

### ISSUE THREAD

**Issue by jcheva123** [ptrumpis/snap-camera-server#1]
Can you explain more the steps? Please!

Configuration - (im stuck here)
Generating SSL Certificate
Importing Root Certificate
Starting Docker
Edit the /etc/hosts file

Thanks

**Comment by ptrumpis** [comment]
@jcheva123 https://www.youtube.com/watch?v=bcsjvWHUr7c

There is also an automatic installer for Windows, so there is no need to install this manually. I will cover the automatic installation tomorrow in another video.
