### ISSUE TITLE
Lens doesn't load

### ISSUE THREAD

**Issue by Droppe1** [ptrumpis/snap-camera-server#109]
OS: [OS Sonoma 14.3.1
Snap Camera Version: 1,21
Signature Patch applied: Yes

Hi, thanks for your work. It is really helpful.

There's lenses I did few month ago and uploaded that works perfectly 
and others I've created few day ago that do not load in the app.

For example:
https://www.snapchat.com/lens/f3b75722654d430fb1948a150bb4d2ad?type=SNAPCODE&metadata=01

https://snapchat.com/unlock/?type=SNAPCODE&uuid=21b761e1e5a84d8bade3ce0fbd594d2d&metadata=01

https://snapchat.com/unlock/?type=SNAPCODE&uuid=4f25a357ecb64caab1cd75f48139b3ac&metadata=01

[Log.txt](https://github.com/ptrumpis/snap-camera-server/files/14402981/Log.txt)

**Comment by ptrumpis** [comment]
### Error: Unknown Blend Mode
These Lenses are created with an unsupported Blend Mode.
There are currently three ways to solve this problem with varying levels of difficulty.

1. Easy - Use Lens Studio 4.36 to publish the Lens.
2. Medium - Fix this issue inside Lens Studio by selecting a different blend mode.
3. Hard - Use Snap Lens Tool to download, fix and manually re-upload the lens to the server.

### How to fix this issue inside Lens Studio
Each image/asset should have a "Blend Mode" dropdown where you can select different blend modes.
One or more of these blend modes does not work with Snap Camera.

<img width="737" alt="d3BT3e0ppx6n_X0yyts39Q" src="https://github.com/ptrumpis/snap-camera-server/assets/116500225/51c34de2-a29d-4eef-9f7c-6755f371be1c">

Source: [Lens Studio Blend Mode Tutorial](https://support.lensstudio.snapchat.com/hc/en-us/community/posts/360072822572--Tutorial-Snap-ML-Blend-Modes-)

Blend Mode "Normal" should work along with:
- "Screen"
- "PremultipliedAlpha"
- "AlphaToCoverage"
- "Disabled"
- "Add"
- "AlphaTest"
- "ColoredGlass"
- "Multiply"
- "Min"
- "Max"

Normal is probably the safest bet.

**Comment by Droppe1** [comment]
The 2 - Medium works perfectly, I own you another coffe.🙏
