### ISSUE TITLE
Still failing to load docker server even using the latest release. Webapp-1 fails to start

### ISSUE THREAD

**Issue by elliereaux** [ptrumpis/snap-camera-server#110]
[+] Running 7/6
 ✔ Network snap-camera-server-321_default       Created                    0.0s 
 ✔ Volume "mysql-db"                            Cre...                     0.0s 
 ✔ Volume "server-storage"                      Created                    0.0s 
 ✔ Container snap-camera-server-321-mysql-1     Created                    0.2s 
 ✔ Container snap-camera-server-321-webapp-1    Created                    0.7s 
 ✔ Container snap-camera-server-321-adminer-1   Created                    0.0s 
 ✔ Container snap-camera-server-321-webproxy-1  Created                    0.0s 
Attaching to adminer-1, mysql-1, webapp-1, webproxy-1
mysql-1     | 2024-02-27 17:22:49+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.36-1.el8 started.
mysql-1     | 2024-02-27 17:22:49+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql-1     | 2024-02-27 17:22:49+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.36-1.el8 started.
adminer-1   | [Tue Feb 27 17:22:49 2024] PHP 7.4.33 Development Server (http://[::]:8080) started
mysql-1     | 2024-02-27 17:22:49+00:00 [Note] [Entrypoint]: Initializing database files
mysql-1     | 2024-02-27T17:22:49.362718Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
mysql-1     | 2024-02-27T17:22:49.362757Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.36) initializing of server in progress as process 80
mysql-1     | 2024-02-27T17:22:49.366070Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
webapp-1    | node:internal/modules/cjs/loader:1031
webapp-1    |   throw err;
webapp-1    |   ^
webapp-1    | 
webapp-1    | Error: Cannot find module '/usr/src/app/server.js'
webapp-1    |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
webapp-1    |     at Function.Module._load (node:internal/modules/cjs/loader:873:27)
webapp-1    |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
webapp-1    |     at node:internal/main/run_main_module:22:47 {
webapp-1    |   code: 'MODULE_NOT_FOUND',
webapp-1    |   requireStack: []
webapp-1    | }
webproxy-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
webproxy-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
webproxy-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
webproxy-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
webproxy-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
webproxy-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
webproxy-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
webproxy-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
webproxy-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: using the "epoll" event method
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: nginx/1.25.4
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: built by gcc 12.2.0 (Debian 12.2.0-14) 
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: OS: Linux 6.6.12-linuxkit
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: start worker processes
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: start worker process 32
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: start worker process 33
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: start worker process 34
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: start worker process 35
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: start worker process 36
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: start worker process 37
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: start worker process 38
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: start worker process 39
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: start worker process 40
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: start worker process 41
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: start worker process 42
webproxy-1  | 2024/02/27 17:22:49 [notice] 1#1: start worker process 43
mysql-1     | 2024-02-27T17:22:49.513413Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
webapp-1 exited with code 1
mysql-1     | 2024-02-27T17:22:50.025026Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
mysql-1     | 2024-02-27 17:22:51+00:00 [Note] [Entrypoint]: Database files initialized
mysql-1     | 2024-02-27 17:22:51+00:00 [Note] [Entrypoint]: Starting temporary server
mysql-1     | 2024-02-27T17:22:51.735607Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
mysql-1     | 2024-02-27T17:22:51.736664Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.36) starting as process 124
mysql-1     | 2024-02-27T17:22:51.742626Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
mysql-1     | 2024-02-27T17:22:51.796789Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mysql-1     | 2024-02-27T17:22:51.923653Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql-1     | 2024-02-27T17:22:51.923673Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
mysql-1     | 2024-02-27T17:22:51.924397Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql-1     | 2024-02-27T17:22:51.930458Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
mysql-1     | 2024-02-27T17:22:51.930468Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.36'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
mysql-1     | 2024-02-27 17:22:51+00:00 [Note] [Entrypoint]: Temporary server started.
mysql-1     | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
mysql-1     | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql-1     | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
mysql-1     | Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
mysql-1     | Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
mysql-1     | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
mysql-1     | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
mysql-1     | 2024-02-27 17:22:52+00:00 [Note] [Entrypoint]: Creating database snapcamera
mysql-1     | 
mysql-1     | 2024-02-27 17:22:52+00:00 [Note] [Entrypoint]: Stopping temporary server
mysql-1     | 2024-02-27T17:22:52.608881Z 11 [System] [MY-013172] [Server] Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.36).
mysql-1     | 2024-02-27T17:22:53.532069Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.36)  MySQL Community Server - GPL.
mysql-1     | 2024-02-27 17:22:53+00:00 [Note] [Entrypoint]: Temporary server stopped
mysql-1     | 
mysql-1     | 2024-02-27 17:22:53+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
mysql-1     | 
mysql-1     | 2024-02-27T17:22:53.777621Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
mysql-1     | 2024-02-27T17:22:53.778076Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.36) starting as process 1
mysql-1     | 2024-02-27T17:22:53.780683Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
mysql-1     | 2024-02-27T17:22:53.809759Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mysql-1     | 2024-02-27T17:22:53.916109Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql-1     | 2024-02-27T17:22:53.916125Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
mysql-1     | 2024-02-27T17:22:53.916798Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql-1     | 2024-02-27T17:22:53.922792Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
mysql-1     | 2024-02-27T17:22:53.922819Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.36'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.

<img width="1202" alt="Screenshot 2024-02-27 at 3 56 05 PM" src="https://github.com/ptrumpis/snap-camera-server/assets/158120675/2b47c9c7-ebcf-4e5b-987d-fca9603ccb4d">

**Comment by ptrumpis** [comment]
Assuming your server files are located at `/Applications/snap-camera-server-321`

Make sure the the path is shared in Docker.
Run these commands in the exact order.

```
cd /Applications/snap-camera-server-321
```

```
docker compose down -v --rmi all --remove-orphans
```

```
docker compose up
```
