### ISSUE TITLE
No input detected, Camera unavailible or being used elsewhere

### ISSUE THREAD

**Issue by valueablelee** [ptrumpis/snap-camera-server#114]
Please make sure the **Wiki** and **Discussions** section does not solve your problem:
- https://github.com/ptrumpis/snap-camera-server/wiki
- https://github.com/ptrumpis/snap-camera-server/discussions

If you are having technical difficulties please provide the following information:
**System (please complete the following information):**
 - OS: [Windows 11
 - Server Version: [server 311]
 - Snap Camera Version: 1.21.1]
 - Signature Patch applied: [yes

**Comment by valueablelee** [comment]
![image_2024-03-03_230719654](https://github.com/ptrumpis/snap-camera-server/assets/134658878/807594c7-40fc-4892-abe4-738624648a42)

**Comment by ptrumpis** [comment]
This is not related to the server... it's probably what it states... your webcam is occupied by another application.
