### ISSUE TITLE
Unable to run Patched Mac Excutable

### ISSUE THREAD

**Issue by akh925** [ptrumpis/snap-camera-server#12]
Greetings!

First, thank you for your hard work on this project. It is much appreciated!
So I have everything set up and working properly on a Mac, except for the Web Lens Download.

I've done the following:

1. Patch the Mac executable using the web patcher provided.
2. Replaced my local "Snap Camera" executable with the patched version downloaded from above. (The downloaded file is a document, I used the terminal to make it executable.)
3. Attempting to run the patched executable results in error: "Snap Camera is damaged and can't be opened."

Any advice? Thank you!

**Comment by akh925** [comment]
Closing, as I managed to resolve this. 😄 
It was Mac's pesky security around application signatures.

**Comment by ptrumpis** [comment]
Glad you made, I published the Mac patch just yesterday and I'm currently producing a video tutorial for Mac users.
