### ISSUE TITLE
Invalid import path (MODULE_NOT_FOUND)

### ISSUE THREAD

**Issue by goodacres** [ptrumpis/snap-camera-server#120]
https://github.com/ptrumpis/snap-camera-server/blob/261845347130ac17a37b68a943439433445fc3c0/server.js#L3

Hey guys - nice work on the app 😎

I just tried to get it running on my local and noticed an issue with the imports for the web-app. 

I changed the path to ./src/endpoints/explorer/category/lenses.js (was ./src/endpoints/category/lenses.js) & now it's working good.

All the best 🙇

**Comment by goodacres** [comment]
Tell a lie - whilst I can build & run after the import change, when I open Snap Camera, it doesn't seem to be making any calls to the proxy despite having the hostfile entry set and being able to access http://studio-app.snapchat.com:

```
 cat /etc/hosts                                      

# Host Database

#

# localhost is used to configure the loopback interface

# when the system is booting. Do not change this entry.

##

127.0.0.1 localhost
255.255.255.255 broadcasthost
::1 localhost
127.0.0.1 studio-app.snapchat.com
```


Tried a few different versions of Snap Camera 1.21, same thing sadly. Any ideas please let me know! 🙇

**Comment by goodacres** [comment]
Some more findings - I installed mitmproxy to be able to dump all outbound http requests from my machine and it looks like I needed to set a hostfile entry for studio-crash.snapchat.com too.

Next issue, the webproxy is return a HTTP 502 Bad Gateway:

```
webproxy-1  | 192.168.65.1 - - [17/Mar/2024:08:52:06 +0000] "GET /vc/v1/explorer/top?country=US&limit=32&offset=0 HTTP/1.1" 502 157 "-" "SnapCamera/1.21.0.0 (macOS 14.4)" "-"
webproxy-1  | 192.168.65.1 - - [17/Mar/2024:08:52:06 +0000] "GET /vc/v1/explorer/categories HTTP/1.1" 502 157 "-" "SnapCamera/1.21.0.0 (macOS 14.4)" "-"
webproxy-1  | 192.168.65.1 - - [17/Mar/2024:08:52:06 +0000] "GET /vc/v1/explorer/scheduled HTTP/1.1" 502 157 "-" "SnapCamera/1.21.0.0 (macOS 14.4)" "-"
webproxy-1  | 2024/03/17 08:52:06 [error] 35#35: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: studio-app.snapchat.com, request: "GET /vc/v1/explorer/categories HTTP/1.1", upstream: "http://172.26.0.4:5645/vc/v1/explorer/categories", host: "studio-app.snapchat.com"
webproxy-1  | 2024/03/17 08:52:06 [error] 34#34: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: studio-app.snapchat.com, request: "GET /vc/v1/explorer/top?country=US&limit=32&offset=0 HTTP/1.1", upstream: "http://172.26.0.4:5645/vc/v1/explorer/top?country=US&limit=32&offset=0", host: "studio-app.snapchat.com"
webproxy-1  | 2024/03/17 08:52:06 [error] 34#34: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: studio-app.snapchat.com, request: "GET /vc/v1/explorer/scheduled HTTP/1.1", upstream: "http://172.26.0.4:5645/vc/v1/explorer/scheduled", host: "studio-app.snapchat.com"
```

Will keep trying and report back

**Comment by ptrumpis** [comment]
Thanks for your report.
Please use the latest release and not the main branch as it is untested and may contain several bugs.
https://github.com/ptrumpis/snap-camera-server/releases/latest
