### ISSUE TITLE
BUG: Unable to start docker-compose via CLI

### ISSUE THREAD

**Issue by MrLazerface** [ptrumpis/snap-camera-server#123]
**Describe the bug**
Trying to run the auto config version of docker-compose.yml via CLI using 'docker compose up' spits out the following errors:

```
PS C:\Snap Camera Server\snap-camera-server-3.1.1> docker compose up
parsing C:\Snap Camera Server\snap-camera-server-3.1.1\docker-compose.yml: yaml: unmarshal errors:
  line 27: mapping key "image" already defined at line 16
  line 28: mapping key "environment" already defined at line 17
  line 42: mapping key "ports" already defined at line 20
  line 45: mapping key "depends_on" already defined at line 22
```
However, using the Docker Desktop GUI, all containers start normally.

**To Reproduce**
1. Start Docker Desktop
2. Open PowerShell, cd to snap camera server
3. run 'docker compose up'
4. See errors

**Expected behavior**
All containers start up as normal, similar to using the Docker desktop GUI.

**System (please complete the following information):**
 - OS: Windows 11 Pro 22H2, build 22621.3007
 - Server Version: 3.1.1
 - Snap Camera Version: 1.21
 - Signature Patch applied: yes
 - Docker desktop: v4.25.1
 - Docker Compose: v2.23.0-desktop.1

**Additional context**
I used the auto config tool to set up this installation. This error is preventing me from automating the startup process.

This may be related to the following issues: https://github.com/docker/compose/issues/10394 and https://github.com/docker/compose/issues/10407
Docker Compose 2.16.0 and earlier handled merge keys differently than 2.17+.

**Comment by ptrumpis** [comment]
Did you edit the file?
Looks like the file is corrupted.

Re-downloading the orignal file should help.
