### ISSUE TITLE
Can't get docker to work

### ISSUE THREAD

**Issue by Bloodrequest** [ptrumpis/snap-camera-server#124]
Please make sure the **Wiki** and **Discussions** section does not solve your problem:
- https://github.com/ptrumpis/snap-camera-server/wiki
- https://github.com/ptrumpis/snap-camera-server/discussions

If you are having technical difficulties please provide the following information:
**System (please complete the following information):**
 - OS: Windows
 - Server Version: 3.2.1
 - Snap Camera Version: 1.21.0

[log.txt](https://github.com/ptrumpis/snap-camera-server/files/14648490/log.txt)

maybe my log can tell you why but i keep getting that on PowerShell

**Comment by ptrumpis** [comment]
I don't know the cause, but you could try this:

1. Remove all containers and volumes in Docker Desktop and try `docker compose up` again.
2. Move the location of the server directory (seems to be inside start menu right now).
3. Run Terminal/Powershell as Administrator might also help.

But those are just my thoughts... This is the first time I've seen this error message.

**Comment by Bloodrequest** [comment]
Ok its all good and running just had to move the directory! thanks for helping!
