### ISSUE TITLE
Nginx not working?

### ISSUE THREAD

**Issue by JasBlack** [ptrumpis/snap-camera-server#133]
- OS: Mac OS
 - Server Version: 3.2.1
 - Snap Camera Version: Not sure (newest)
 - Signature Patch applied: I didn't get that far yet
 
 Hello, I am following your instructions and youtube video, but I seem to have a problem with the Docker step.
 
 It seems like the Nginx cannot read the SSL?
 
 I tried using ChatGPT to help solve it, but I never managed to figure it out. Any help appreciated.
 
 Thanks
 
<img width="1022" alt="Screenshot 2024-04-16 at 18 09 59" src="https://github.com/ptrumpis/snap-camera-server/assets/105222101/64b9ac26-cd13-48a9-ac96-836dc9cd8f36">

 
 (base) db@DBs-MacBook-Pro snap-camera-server-3.2.1 % docker compose up                                                                       
[+] Running 4/0
 ⠿ Container snap-camera-server-321-mysql-1     Running                                                                                                                                 0.0s
 ⠿ Container snap-camera-server-321-adminer-1   Running                                                                                                                                 0.0s
 ⠿ Container snap-camera-server-321-webapp-1    Running                                                                                                                                 0.0s
 ⠿ Container snap-camera-server-321-webproxy-1  Created                                                                                                                                 0.0s
Attaching to snap-camera-server-321-adminer-1, snap-camera-server-321-mysql-1, snap-camera-server-321-webapp-1, snap-camera-server-321-webproxy-1
snap-camera-server-321-webproxy-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
snap-camera-server-321-webproxy-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
snap-camera-server-321-webproxy-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
snap-camera-server-321-webproxy-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
snap-camera-server-321-webproxy-1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
snap-camera-server-321-webproxy-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
snap-camera-server-321-webproxy-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
snap-camera-server-321-webproxy-1  | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
snap-camera-server-321-webproxy-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
snap-camera-server-321-webproxy-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
snap-camera-server-321-webproxy-1  | 2024/04/16 17:15:20 [emerg] 1#1: cannot load certificate "/etc/ssl/certs/studio-app.snapchat.com.crt": BIO_new_file() failed (SSL: error:80000001:system library::Operation not permitted:calling fopen(/etc/ssl/certs/studio-app.snapchat.com.crt, r) error:10080002:BIO routines::system lib)
snap-camera-server-321-webproxy-1  | nginx: [emerg] cannot load certificate "/etc/ssl/certs/studio-app.snapchat.com.crt": BIO_new_file() failed (SSL: error:80000001:system library::Operation not permitted:calling fopen(/etc/ssl/certs/studio-app.snapchat.com.crt, r) error:10080002:BIO routines::system lib)
snap-camera-server-321-webproxy-1 exited with code 1

**Comment by ptrumpis** [comment]
Try this: https://github.com/ptrumpis/snap-camera-server/discussions/73#discussioncomment-7256618

Just make sure the command matches your server directory

**Comment by JasBlack** [comment]
Hello thanks for your speedy reply. Unfortunately that #73 fix did not work for me. I also tried deleting everything and starting again, but having exactly the same issue. Here are some screenshots, maybe you understand the problem?

Thanks
<img width="924" alt="Screenshot 2024-04-17 at 15 21 49" src="https://github.com/ptrumpis/snap-camera-server/assets/105222101/ade00e1e-a718-4de7-a549-a7faa3979401">
<img width="1177" alt="Screenshot 2024-04-17 at 16 12 58" src="https://github.com/ptrumpis/snap-camera-server/assets/105222101/c54ae5d1-3b43-4179-8358-26cbe9a0b758">

**Comment by ptrumpis** [comment]
See https://github.com/ptrumpis/snap-camera-server/discussions/76

**Comment by JasBlack** [comment]
I think I messed up because I installed the patch and now Snapchat wont open.

Following this video.
https://www.youtube.com/watch?v=lJhL7bA7GGA

I am guessing now that it was not necessary for me to install the patch? I had version 3.2.1

Snapchat would not open at all after following the video. So I uninstalled and deleted everything and reinstalled it, and now it opens, but none of the filters actually work!

So I am not sure what to do now, should I try the patch again? 

Or start from step 1 and try to start the whole thing over again with Docker etc?
<img width="938" alt="Screenshot 2024-04-18 at 14 31 56" src="https://github.com/ptrumpis/snap-camera-server/assets/105222101/efe3ea84-068c-4603-8440-7e9f7c045735">

**Comment by JasBlack** [comment]
i tried again with the patch and followed your instructions, and got this. 

<img width="417" alt="Screenshot 2024-04-18 at 15 20 57" src="https://github.com/ptrumpis/snap-camera-server/assets/105222101/36d9b719-7aed-4971-bf0d-d2005faa02ac">


(base) db@DBs-MacBook-Pro ~ % chmod +x "/Applications/Snap Camera.app/Contents/MacOS/Snap Camera"
(base) db@DBs-MacBook-Pro ~ % sudo codesign --remove-signature "/Applications/Snap Camera.app"
Password:
(base) db@DBs-MacBook-Pro ~ % sudo xattr -cr "/Applications/Snap Camera.app"
(base) db@DBs-MacBook-Pro ~ % sudo spctl --add "/Applications/Snap Camera.app"
(base) db@DBs-MacBook-Pro ~ % sudo codesign --force --deep --sign - "/Applications/Snap Camera.app"
(base) db@DBs-MacBook-Pro ~ %

**Comment by JasBlack** [comment]
ok got it working again, but still the filters do not show. 
<img width="937" alt="Screenshot 2024-04-18 at 15 33 04" src="https://github.com/ptrumpis/snap-camera-server/assets/105222101/61ffc5a3-2c57-4234-911f-848a099e9074">

**Comment by ptrumpis** [comment]
Please open a new "Lens not Working" issue with your application log file attached.
