### ISSUE TITLE
Lens not Working - none of them

### ISSUE THREAD

**Issue by JasBlack** [ptrumpis/snap-camera-server#134]
**System Information (please complete the following information):**
 - OS: Mac OS 14.2.1
 - Snap Camera Version:  1.21
 - Signature Patch applied: yes

**Please follow these steps to provide detailed information**
1. Open Snap Camera
2. Select all Lenses that are not working in your app - **All of them not working**
3. Copy and attach the Snap Camera log file to this ticket
   - (Windows): %USERPROFILE%\AppData\Local\Snap\Snap Camera\Log.txt 
   - (Mac OS): /Users/{YOUR_USER_NAME}/Library/Preferences/Snap/Snap Camera/Log.txt

**Please also provide the lens share link** - What is this?

I have never had issues with my macbook, but since trying to install snapcam, it has frozen multiple times and I had to hard restart and reboot. Even just trying to open the application, I have some glitches where the icon just hovers over everything else on my macbook and will not open. It also prompts me for the "login" keychain password each time.

Any help appreciated, thanks.

<img width="303" alt="Screenshot 2024-04-20 at 15 25 46" src="https://github.com/ptrumpis/snap-camera-server/assets/105222101/ad88a41d-bb11-4004-a51e-d38b4a7d2589">

<img width="424" alt="Screenshot 2024-04-20 at 15 42 17" src="https://github.com/ptrumpis/snap-camera-server/assets/105222101/3d23ca6c-ed54-4dad-90a8-f0cf964f1075">

<img width="1069" alt="Screenshot 2024-04-20 at 15 43 25" src="https://github.com/ptrumpis/snap-camera-server/assets/105222101/bd711280-7f1d-4edb-893d-f9b9cce2dd83">

**Comment by JasBlack** [comment]
[Log.txt](https://github.com/ptrumpis/snap-camera-server/files/15048625/Log.txt)


log file attached

**Comment by ptrumpis** [comment]
1. Please check if these urls are reachable:
   - https://studio-app.snapchat.com:443
   - http://studio-app.snapchat.com:80
   - http://127.0.0.1:80

2. Please download and run:
   https://github.com/ptrumpis/snap-camera-signature-patch/blob/master/macOS/errorfix.sh
   And report the output of the script.

**Comment by paxinstudio** [comment]
> 1. Please check if these urls are reachable:
>        
>        * https://studio-app.snapchat.com:443
>        * http://studio-app.snapchat.com:80
>        * http://127.0.0.1:80
> 
>     2. Please download and run:
>        https://github.com/ptrumpis/snap-camera-signature-patch/blob/master/macOS/errorfix.sh
>        And report the output of the script.

Same exact issue with me, on Macbook Pro M1 Max
Ran the errorfix script, but still doesn't load for me too.

**Comment by ptrumpis** [comment]
> And report the output of the script.

@ppstudio13 You need to open another ticket
