### ISSUE TITLE
Infinite loading for lens

### ISSUE THREAD

**Issue by mrh270188** [ptrumpis/snap-camera-server#138]
**System Information (please complete the following information):**
 - OS: Mac OS
 - Snap Camera Version: 1.21]
 - Signature Patch applied: yes

I'm not able to use the following lens. I'm sure I have patched the snap camera binary. Any help would be appreciated.

Link to the Lens: https://www.snapchat.com/lens/7e8a31f3f85c485ca64299f06a4ed2a6?type=SNAPCODE&metadata=01
Log: [Log.txt](https://github.com/ptrumpis/snap-camera-server/files/15213189/Log.txt)

**Comment by ptrumpis** [comment]
Try this:
1. Right click the Snap Camera Application
2. Click Get Info
3. Click Open Using Rosetta

You will need to fully close and re-open Snap Camera (It keeps running in the background)
