### ISSUE TITLE
Not able to download new filters after applying patch

### ISSUE THREAD

**Issue by REALtony4twenty** [ptrumpis/snap-camera-server#15]
[Log.txt](https://github.com/ptrumpis/snap-camera-server/files/11095518/Log.txt)

I used "https://ptrumpis.github.io/snap-camera-signature-patch/" and made sure I got a green check mark before pressing "apply patch"

**Comment by ptrumpis** [comment]
There is a known problem with AMD graphic cards. This might be the case here.
Snapchat never fixed the problem.

- https://community.snap.com/snapar/discussion/1388/amd-snap-camera-issues
- https://support.lensstudio.snapchat.com/hc/en-us/community/posts/360077301552-Snap-Camera-filters-aren-t-working-properly-help-

You could other filters or you can try to use Snap Camera 1.19

**Comment by REALtony4twenty** [comment]
I will as soon as I can

**Comment by ptrumpis** [comment]
To make things easier:
This search script will output the information I need, copy and save as *.bat file or download and run the attached file.

```bat
@echo off
%SYSTEMDRIVE%
cd %SYSTEMROOT%
cd system32
for /r %%x in (*amdocl*) do echo "%%x"
pause
```

[search.zip](https://github.com/ptrumpis/snap-camera-server/files/11095797/search.zip)

**Comment by ptrumpis** [comment]
Lucky for you I'm bored 😄

Try this fix and see if it works
https://github.com/ptrumpis/OpenCL-AMD-GPU

**Comment by REALtony4twenty** [comment]
oddly enough, I woke up this morning and ran it to show my girlfriend what I was working on. All of a sudden it No longer was stuck constantly loading. Though they do not work still which I assume is based on what you previously stated. I check for the amdoc164.dll and I didnt seem to have one so I used to the Fix you made while bored lol It added the file to my file repository but it did not seem to effect my snap camera in any way. I tried using one of the filters that leaves a weird box around or on my head and they were still there. Thankyou for all the help. Not sure why the patch didn't take effect right away yesterday. I was in the process of making a video about installing of this! so hopefully soon I will have that released.

**Comment by ptrumpis** [comment]
Sometime web lenses will not load (it's an issue related to their web server) removing and re-pasting lens links into the search field can resolve the problem.

The file is AMDOCL, it looks like a 1 but it's the lowercase L.

Can you run the search script attached if you have time?
It should output all amdocl files on your system (there should be multiple).
If the file is missing, downloading the file could possibly fix the head boxing issue. 

[search.zip](https://github.com/ptrumpis/snap-camera-server/files/11102992/search.zip)

**Comment by REALtony4twenty** [comment]
"C:\Windows\System32\DriverStore\FileRepository\u0384804.inf_amd64_41ca4ca6939f5e56\B384763\amdocl32.dll"
"C:\Windows\System32\DriverStore\FileRepository\u0384804.inf_amd64_41ca4ca6939f5e56\B384763\amdocl64.dll" 

returned^
