### ISSUE TITLE
Issue With Docker

### ISSUE THREAD

**Issue by AngelDoesstuffs** [ptrumpis/snap-camera-server#151]
Docker seems to be having an issue loading because it can't use port 80, and I can't free the port up because it appears windows is using it, I used the auto configuration tool and was a lil surprised when docker was fighting with windows, if you have a fix, I'd love to hear it 👍 
![image](https://github.com/user-attachments/assets/0e6408a4-512b-485f-a525-63b0ed77dc3e)
![image](https://github.com/user-attachments/assets/a0af03c3-8aa8-4f96-832c-d815d7fc0b3e)

**Comment by ptrumpis** [comment]
Edit your `.env` file and change `NGINX_LOCAL_PORT=80` to another number.

e.g.:
`NGINX_LOCAL_PORT=1080`

**Comment by AngelDoesstuffs** [comment]
Okay, as suggested, but it's still erroring out
![image](https://github.com/user-attachments/assets/1842c727-4757-4ceb-9f25-3e8bd6c2e86a)
![image](https://github.com/user-attachments/assets/9214dcbf-1f2d-4e48-b5f5-6c39a3841633)

**Comment by ptrumpis** [comment]
You can try to run auto configuration tool again. This should refresh the port number.

**Comment by AngelDoesstuffs** [comment]
That did seem to fix that issue, but apparently there's a new one 
![image](https://github.com/user-attachments/assets/099271ea-7d55-46de-bda1-03e3446c7fc3)
![image](https://github.com/user-attachments/assets/f52e5f29-8778-4d95-92bf-a538be64dacb)

**Comment by ptrumpis** [comment]
You can try to remove the
- MySQL Container
- MySQL Image
- MySQL Volume

And then restart everything. A new fresh MySQL server will be set up.
If this doesn't work... try again but this time remove all containers, images and volumes.

You can refer to the upgrade guide on how removal works.
https://github.com/ptrumpis/snap-camera-server/wiki/Upgrading-Server-v2.x-to-v3.x#docker-desktop

**Comment by AngelDoesstuffs** [comment]
Tysm! You're a life saver and I appreciate the help!
