### ISSUE TITLE
Mac Tutorial

### ISSUE THREAD

**Issue by Hansleonel** [ptrumpis/snap-camera-server#16]
Do you have a mac tutorial please?, since yesterday the jaku version is failing

**Comment by ptrumpis** [comment]
There are multiple by now

[Installing Snap Camera Server on Mac OS](https://www.youtube.com/watch?v=b2ILHJaD1T4)
[Patching Snap Camera on Mac OS (Signature Patch)](https://www.youtube.com/watch?v=lJhL7bA7GGA)
