### ISSUE TITLE
docker compose failing with this error - macOS

### ISSUE THREAD

**Issue by yakudZZZa** [ptrumpis/snap-camera-server#17]
```
username@nickname-MacBook-Pro snap-camera-server-3.0.1 % docker compose up
[+] Running 0/1
 ⠋ Container snap-camera-server-301-webproxy-1  Creating                                   0.1s
Error response from daemon: image with reference nginx was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8
```

**Comment by ptrumpis** [comment]
https://github.com/ptrumpis/snap-camera-server/wiki/Docker-on-Apple-M1-(ARM64)

**Comment by yakudZZZa** [comment]
I have read the instructions and my config is:
`version: '3.8'

services:
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
    volumes:
      - db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d:ro

  adminer:
    platform: linux/amd64
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DESIGN=${ADMINER_DESIGN}
    ports:
      - ${ADMINER_LOCAL_PORT}:${ADMINER_DOCKER_PORT}
    depends_on:
      - mysql

  webproxy:
    platform: linux/amd64
    image: nginx
    environment:
      - WEBAPP_PORT=${APP_DOCKER_PORT}
      - HTTP_PORT=${NGINX_DOCKER_PORT}
      - WWW_ROOT=${NGINX_WWW_ROOT}
    volumes:
      - ./ssl/studio-app.snapchat.com.crt:/etc/ssl/certs/studio-app.snapchat.com.crt:ro
      - ./ssl/studio-app.snapchat.com.key:/etc/ssl/private/studio-app.snapchat.com.key:ro
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/theme:/etc/nginx/theme:ro
      - ./nginx/snap-camera-categories-media:${NGINX_WWW_ROOT}/snap-camera-categories-media:ro
      - ./nginx/snap-camera-media:${NGINX_WWW_ROOT}/snap-camera-media:ro
      - ./nginx/snap-camera-media-alt:${NGINX_WWW_ROOT}/snap-camera-media-alt:ro
      - ./import:${NGINX_WWW_ROOT}/import
      - storage:${NGINX_WWW_ROOT}
    ports:
      - ${NGINX_LOCAL_PORT}:${NGINX_DOCKER_PORT}
      - 443:443
    depends_on:
      - webapp

  webapp:
    platform: linux/amd64
    build: .
    environment:
      - DB_HOST=mysql
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PORT=${MYSQL_DOCKER_PORT}
      - PORT=${APP_DOCKER_PORT}
      - STORAGE_SERVER=http://studio-app.snapchat.com:${NGINX_LOCAL_PORT}
      - STORAGE_PATH=/var/lib/snapcamera
      - IMPORT_DIR=import
      - MEDIA_DIR=snap-camera-media
      - MEDIA_DIR_ALT=snap-camera-media-alt
    volumes:
      # content of snap-camera-media (MEDIA_DIR) is not getting included automatically through storage
      - ./nginx/snap-camera-media:/var/lib/snapcamera/snap-camera-media:ro
      - ./import:/var/lib/snapcamera/import
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - storage:/var/lib/snapcamera
    ports:
      - ${APP_LOCAL_PORT}:${APP_DOCKER_PORT}
    depends_on:
      - mysql

volumes:
  storage:
    name: server-storage
  db:
    name: mysql-db`

**Comment by ptrumpis** [comment]
You probably have to delete your existing containers
run `docker compose down`

and/or manually remove any old docker images inside docker desktop

after cleaning `docker compose up` should work

**Comment by yakudZZZa** [comment]
nope, there is the same
```
username@nickname-MacBook-Pro snap-camera-server-3.0.1 % docker compose down
[+] Running 4/4
 ⠿ Container snap-camera-server-301-webapp-1   Removed                                     0.1s
 ⠿ Container snap-camera-server-301-adminer-1  Removed                                     0.1s
 ⠿ Container snap-camera-server-301-mysql-1    Removed                                     0.0s
 ⠿ Network snap-camera-server-301_default      Removed                                     0.1s
username@nickname-MacBook-Pro snap-camera-server-3.0.1 % docker compose up  
[+] Running 4/4
 ⠿ Network snap-camera-server-301_default       Created                                    0.0s
 ⠿ Container snap-camera-server-301-mysql-1     Created                                    0.1s
 ⠿ Container snap-camera-server-301-adminer-1   Created                                    0.1s
 ⠿ Container snap-camera-server-301-webapp-1    Created                                    1.8s
 ⠋ Container snap-camera-server-301-webproxy-1  Creating                                   0.1s
Error response from daemon: image with reference nginx was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8
```

**Comment by ptrumpis** [comment]
Hmm try to remove the platform line from webproxy

```yml
webproxy:
    image: nginx
```

If it doesn't work, try to add a tag after nginx

```yml
  webproxy:
    platform: linux/amd64
    image: nginx:1.22
```

Other possible tags could be:
1.23 | latest | stable

**Comment by yakudZZZa** [comment]
Removing the "platform" line helped me.
However, when the process went further, apparently not all lenses are saved, because a lot of similar errors fell out in the terminal:
```
snap-camera-server-301-webapp-1    | Downloading https://lens-storage.storage.googleapis.com/png/0ddd45e4b5244ae5a38fa5df396e98a4
snap-camera-server-301-webapp-1    | downloadFile error: FetchError: Invalid response body while trying to fetch https://lens-storage.storage.googleapis.com/png/edf081d1d4fb42a3adbc3d46ebbcd264: aborted
snap-camera-server-301-webapp-1    |     at consumeBody (file:///usr/src/app/node_modules/node-fetch/src/body.js:234:60)
snap-camera-server-301-webapp-1    |     at runMicrotasks (<anonymous>)
snap-camera-server-301-webapp-1    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
snap-camera-server-301-webapp-1    |     at async downloadFile (file:///usr/src/app/src/utils/storage.js:207:24)
snap-camera-server-301-webapp-1    |     at async savePNG (file:///usr/src/app/src/utils/storage.js:134:13)
snap-camera-server-301-webapp-1    |     at async Module.saveLens (file:///usr/src/app/src/utils/storage.js:22:9)
snap-camera-server-301-webapp-1    |     at async Module.downloadLens (file:///usr/src/app/src/utils/helper.js:121:20)
snap-camera-server-301-webapp-1    |     at async Query.onResult (file:///usr/src/app/src/utils/db.js:258:25) {
snap-camera-server-301-webapp-1    |   type: 'system',
snap-camera-server-301-webapp-1    |   errno: 'ECONNRESET',
snap-camera-server-301-webapp-1    |   code: 'ECONNRESET',
snap-camera-server-301-webapp-1    |   erroredSysCall: undefined
snap-camera-server-301-webapp-1    | } https://lens-storage.storage.googleapis.com/png/edf081d1d4fb42a3adbc3d46ebbcd264
```
The server is working fine, but some of the lenses cannot be loaded. For example, when I try to turn on one of these lenses, the Webproxy terminal writes only this and that's all:
```
2023-04-02 11:37:59 172.18.0.1 - - [02/Apr/2023:08:37:59 +0000] "GET /vc/v1/explorer/unlock?uid=61838800878 HTTP/1.1" 200 363 "-" "SnapCamera/1.21.0.0 (macOS 13.3)" "-"
2023-04-02 11:37:59 172.18.0.1 - - [02/Apr/2023:08:37:59 +0000] "GET /3/c8FUojs13utIRDnlf9Ntm?bo=EhgaABoAMgF9OgEEQgYIyr_zoAZIAlASYAE%3D&uc=18 HTTP/1.1" 200 86190 "-" "SnapCamera/1.21.0.0 (macOS 13.3)" "-"
```
At the same time, if I turn on a lens that can load, the Webproxy terminal writes:
```
2023-04-02 11:41:57 172.18.0.1 - - [02/Apr/2023:08:41:57 +0000] "GET /png/9f0b0619-1852-31af-b853-6f6fa18faaa2_320_d2876207-2ffb-45c3-811b-9c2cd39bf2bd.png HTTP/1.1" 200 57810 "-" "SnapCamera/1.21.0.0 (macOS 13.3)" "-"
2023-04-02 11:41:57 172.18.0.1 - - [02/Apr/2023:08:41:57 +0000] "GET /vc/v1/explorer/unlock?uid=60115820875 HTTP/1.1" 200 2209 "-" "SnapCamera/1.21.0.0 (macOS 13.3)" "-"
2023-04-02 11:41:58 172.18.0.1 - - [02/Apr/2023:08:41:58 +0000] "POST /vc/v1/explorer/lenses HTTP/1.1" 200 908 "-" "SnapCamera/1.21.0.0 (macOS 13.3)" "-"
2023-04-02 11:41:58 172.18.0.1 - - [02/Apr/2023:08:41:58 +0000] "GET /vc/v1/explorer/unlock?uid=60115820875 HTTP/1.1" 200 2224 "-" "SnapCamera/1.21.0.0 (macOS 13.3)" "-"
```
Apparently there is an error somewhere in the parsing of some lenses.

**Comment by ptrumpis** [comment]
Did you apply the signature patch?
