### ISSUE TITLE
lenses are infinite loading

### ISSUE THREAD

**Issue by Fan4eGGG** [ptrumpis/snap-camera-server#18]
do exactly as in guide. start snapcam and tried couple filter and they loads [like that](https://prnt.sc/afRovdnR5Thv) and.. nothing.
what do i wrong?

**Comment by ptrumpis** [comment]
Please follow these steps to provide detailed information
1. Open Snap Camera
2. Select all Lenses that are not working in your app
3. Copy and attach the file %USERPROFILE%\AppData\Local\Snap\Snap Camera\Log.txt to this ticket

Please also provide the lens share link

**Comment by Fan4eGGG** [comment]
> Select all Lenses that are not working

ehm.. how? and why

> Please also provide the lens share link

all of them? theres 50/50. for example [this](https://lens.snapchat.com/5c893df222034157ace1e71708ab1182) or [that](https://lens.snapchat.com/229b8ad6de8e428ca2ba6a77f6f0e363).

log file here: 
[Log.txt](https://github.com/ptrumpis/snap-camera-server/files/11192892/Log.txt)

**Comment by ptrumpis** [comment]
If you don't select them they will not be included in the log file.
But you probably didn't apply the signature patch.

> "Checksum doesn't match for lens archive: 57939720876"

**Comment by Fan4eGGG** [comment]
just do it again and nothing.
i dwnld ver 1.21 is that right?

**Comment by Fan4eGGG** [comment]
well. okay i reinstall snap camera and do all over again and it seems.. everything works now. thanks for ur help!

i have a question about **Docker**: is there any way to make all filters work without Docker, because it (_together with the vmmem process_) eats up 90% of my RAM :(

**Comment by ptrumpis** [comment]
You can bind your lenses to Hotkeys if you add them to your list of favorites.
You don't have to start the Docker Server to use Hotkeys.

This might help you to optimize your Docker settings to use less resources:
- [Optimize Docker Settings](https://docs.docker.com/desktop/settings/windows/)
- [Optimize WSL2 Settings](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#configuration-setting-for-wslconfig)

**Comment by Fan4eGGG** [comment]
nah. hotkey didnt work for lenses which unavailable wo/snap server
