### ISSUE TITLE
[LENS] 

### ISSUE THREAD

**Issue by marklee1219** [ptrumpis/snap-camera-server#19]
**System Information (please complete the following information):**
 - OS: [e.g. Windows, Mac OS] -Window11
 - Snap Camera Version: [e.g. 1.19, 1.20, 1.21] 1.21
 - Signature Patch applied: [yes or no] Yes

**Please follow these steps to provide detailed information**
1. Open Snap Camera 
2. Select all Lenses that are not working in your app
3. Copy and attach the file %USERPROFILE%\AppData\Local\Snap\Snap Camera\Log.txt to this ticket
[Log.txt](https://github.com/ptrumpis/snap-camera-server/files/11184020/Log.txt)

**Please also provide the lens share link**
https://lens.snapchat.com/de04d9e201ac456f9cd9e0c193cecdf3?sender_web_id=ff6eea5d-13ad-4c27-b7e3-367dffb3d34e&device_type=desktop&is_copy_url=true

**Comment by ptrumpis** [comment]
I just send you an invitation link to https://github.com/snapcamera/snap-camera-assets

You need to download this folder and place it inside your Snap Camera folder
- [CoreResources.bundle](https://github.com/snapcamera/snap-camera-assets/tree/latest/CoreResources.bundle)

And download this folder and place it into your Snap Camera\Resources folder
- [PrecachedAssets.bundle](https://github.com/snapcamera/snap-camera-assets/tree/latest/PrecachedAssets.bundle)

---

This files are required to do an unofficial update as explained here:
- https://github.com/ptrumpis/snap-camera-server/wiki/Updating-Snap-Camera-(Unofficial)
- https://github.com/ptrumpis/snap-camera-server/wiki/Snap-Camera-Assets

**Comment by Pickymarker** [comment]
links don't work
