### ISSUE TITLE
[LENS]

### ISSUE THREAD

**Issue by marklee1219** [ptrumpis/snap-camera-server#21]
**System Information (please complete the following information):**
 - OS: [e.g. Windows, Mac OS] Windows 11 
 - Snap Camera Version: [e.g. 1.19, 1.20, 1.21] 1.21
 - Signature Patch applied: [yes or no] Yes

**Please follow these steps to provide detailed information**
1. Open Snap Camera
2. Select all Lenses that are not working in your app
3. Copy and attach the file %USERPROFILE%\AppData\Local\Snap\Snap Camera\Log.txt to this ticket
[Log.txt](https://github.com/ptrumpis/snap-camera-server/files/11186317/Log.txt)

**Please also provide the lens share link**
https://snapchat.com/unlock/?type=SNAPCODE&uuid=de04d9e201ac456f9cd9e0c193cecdf3&metadata=01
punk9652
Lens ID: 63a91836-315e-4ec0-8d83-0654cf65d608

P.S.
The Snap Lens has been published for approximately one week. Interestingly, when I used Snap Camera after launching the Docker server, I was able to locate the lens using the keyword "17mile". However, upon attempting to use the lens, it failed to function and caused the screen to freeze. Notably, other lenses operate without issue.

**Comment by ptrumpis** [comment]
https://github.com/ptrumpis/snap-camera-server/issues/19#issuecomment-1500987726
