### ISSUE TITLE
Problem with Cache Import

### ISSUE THREAD

**Issue by magikarp28** [ptrumpis/snap-camera-server#3]
Following the tutorial everything works fine but now I need to import some cached lenses I have.

When I press the button to import cache I get this error:
POST http://127.0.0.1/vc/v1/import/cache net::ERR_BLOCKED_BY_CLIENT

I do this when the server is running and try to import the settings.json from my snap camera folder in the snap camera folder where the cache folder is located and the files inside that cache folder.

**Comment by ptrumpis** [comment]
@magikarp28 What browser are you using?

**Comment by magikarp28** [comment]
> @magikarp28 What browser are you using?

Brave and Chrome give that error.
Just tried firefox and it gives a CORS policy error instead. 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1/vc/v1/import/cache. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Edge gives both errors.

**Comment by ptrumpis** [comment]
@magikarp28 I updated the code it should be fixed now
You just have to download and replace this file

```
https://raw.githubusercontent.com/ptrumpis/snap-camera-server/main/nginx/default.conf.template
```

**Comment by ptrumpis** [comment]
Btw. I am able to bring **ALL** lenses back not only cached ones...

New version 3.0.0 is coming which will fix alle the missing lens problems

**Comment by magikarp28** [comment]
Awsome, fixed!
