### ISSUE TITLE
Can't finish install on Docker Compose Up

### ISSUE THREAD

**Issue by jarreee11** [ptrumpis/snap-camera-server#36]
Hey.  I'm stuck on the terminal after docker compose up, where it says "Attaching to snap-camera-server-300-adminer-1, snap-camera-server-300-mysql-1, snap-camera-server-300-webapp-1, snap-camera-server-300-webproxy-1" and doesn't move any farther. Any ideas?

I'm on MacOS 12.4 on an i9 chip, 
Snap Camera 1.21
signature patch applied
Server 3.0.0

If you are having technical difficulties please provide the following information:
**System (please complete the following information):**
 - OS: [e.g. Windows, Mac OS]
 - Server Version: [e.g. 2.0.6, , 3.0.0, 3.0.1, ...]
 - Snap Camera Version: [e.g. 1.19, 1.20, 1.21]
 - Signature Patch applied: [yes or no]

**Comment by jarreee11** [comment]
Also I've tried compose docker down to remove everything, and then docker up.  The servers appear in Docker but don't run.  Never gets past  
<img width="638" alt="Screen Shot 2023-06-21 at 3 47 47 PM" src="https://github.com/ptrumpis/snap-camera-server/assets/137334400/13348e43-8a9b-42da-a474-f5ecde263347">

I appreciate your work on this!

**Comment by ptrumpis** [comment]
What exactly do you mean by stuck? For how long did you wait?

Does everything show up in Docker Desktop?
If it shows up in Docker Desktop you don't need to run "docker compose up" again.
Everything should be working as intended if there is no error message.

You should be able to start the server with the play button.

**Comment by jarreee11** [comment]
I waited maybe an hour. It showed up Docker and I ran but it didn’t
successfully run in docker when I hit play. I ended up using an alternative
method with some success. But trying on another computer in a week so
hopefully will work better. Thanks for getting back to me.
