### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Fan4eGGG** [ptrumpis/snap-camera-server#39]
A strange error came out of nowhere.
Yesterday everything was working, today [THIS](https://i.imgur.com/nBP9p82.jpg) error appears.
What do I do?

**Comment by Fan4eGGG** [comment]
I don't know if the port is busy right now, how do I check it? Or fix it?

**Comment by ptrumpis** [comment]
> I don't know if the port is busy right now, how do I check it? Or fix it?

How to check depends on your operating system and available tools.
I would run the command `netstat -np TCP | grep :5645` on my Windows bash / powershell

If it was working yesterday you must have changed something on your system.
e.g. Installed new software, updated your operating system.
It could be your firewall blocking the port.

You can try to edit the `.env` file and change `APP_LOCAL_PORT` to `15645` or any other number above `5000`
https://github.com/ptrumpis/snap-camera-server/blob/main/example.env#L47C20-L47C20

**Comment by Fan4eGGG** [comment]
`netstat -np TCP | grep :5645` give me nothing. it says 

> is not recognized as an internal or external command operable program or batch file

**Comment by Fan4eGGG** [comment]
i think the command is broken on my pc :D
it shows me [this](https://prnt.sc/CJg1cGZhKm1C), but its on russian

**Comment by ptrumpis** [comment]
Well its probably not available on your computer then.
Just `netstat -np TCP` shoud work though, it will show a list of all your open ports.

**Comment by Fan4eGGG** [comment]
btw, I changed the port to **15645** and it still gives the same error.

**Comment by ptrumpis** [comment]
> `netstat -np TCP` It didn't show me port 15645 or 5645. I think I'm doing something wrong.

Because the port is not occupied -> Check your Firewall

**Comment by Fan4eGGG** [comment]
What exactly am I supposed to find there? Can you give me a hint?

**Comment by ptrumpis** [comment]
You should grant access to Docker and/or allow tcp port 5645 (and all other ports if necessary).

You can lookup tutorials on the internet on how to do that.

**Comment by Fan4eGGG** [comment]
oh. I gave full access to these two ports in my firewall and I still get the same error.

**Comment by ptrumpis** [comment]
You need to check your Docker settings.
There are multiple ways to reduce memory but it depends on your settings and your system.
The official Docker page can provide more details on this.

If you have WSL2 enabled in your settings you should also check the official Microsoft WSL page on how du reduce memory.

Creating a file called `.wslconfig` in your `%USERPROFILE%` folder can also help.

_.wslconfig_
```ini
[wsl2] 
memory=2GB
processors=2
swap=2GB
```

**Comment by Fan4eGGG** [comment]
Yes, now wsl consumes no more than 2gb.
but can I reduce it further? won't it hurt Docker? what is the minimum amount of RAM I can set?

**Comment by Fan4eGGG** [comment]
yeah ok. моя проблема решилась, так что думаю топик можно закрыть.
спасибо за помощь.
