### ISSUE TITLE
Lens keeps loading/not working

### ISSUE THREAD

**Issue by AliMohameddddd** [ptrumpis/snap-camera-server#41]
[Log.txt](https://github.com/ptrumpis/snap-camera-server/files/12139990/Log.txt)
**System Information (please complete the following information):**
 - OS: [Windows]
 - Snap Camera Version: [1.21]
 - Signature Patch applied: [yes]

**Please follow these steps to provide detailed information**
1. Open Snap Camera
2. Select all Lenses that are not working in your app (literally this is the only one i want and i can locate it location in the cache)
3. Copy and attach the Snap Camera log file to this ticket
   - (Windows): [Log.txt](https://github.com/ptrumpis/snap-camera-server/files/12139989/Log.txt)
   - (Mac OS): /Users/{YOUR_USER_NAME}/Library/Preferences/Snap/Snap Camera/Log.txt

**Please also provide the lens share link**
https://lens.snapchat.com/1d88d03318714f45a274a5fd92c2504d

**Comment by ptrumpis** [comment]
> "Checksum doesn't match for lens archive: 49902940876"

Signature patch is not applied correctly.
You need to apply it again.

**Comment by AliMohameddddd** [comment]
Done....THANKS VERY MUCH!!!!!!!!!! YOU THE FUCKING MAN!
