### ISSUE TITLE
Lens not loading

### ISSUE THREAD

**Issue by Droppe1** [ptrumpis/snap-camera-server#44]
**System Information (please complete the following information):**
 - OS:  Mac OS Ventura 13.4.1
 - Snap Camera Version: 1.21
 - Signature Patch applied: yes (mac OS | NCS)

**Please follow these steps to provide detailed information**
1. Open Snap Camera
2. Select all Lenses that are not working in your app
3. Copy and attach the Snap Camera log file to this ticket
   - (Windows): %USERPROFILE%\AppData\Local\Snap\Snap Camera\Log.txt 
   - (Mac OS): /Users/{YOUR_USER_NAME}/Library/Preferences/Snap/Snap Camera/Log.txt

[Log.txt](https://github.com/ptrumpis/snap-camera-server/files/12162832/Log.txt)

**Please also provide the lens share link**

https://www.snapchat.com/unlock/?type=SNAPCODE&uuid=0d48065a9ae846c88695b93ea4451bd7&metadata=01

**Comment by ptrumpis** [comment]
> "Checksum doesn't match for lens archive: 62836700897"

The signature patch is not applied correctly on your snap camera application.

You may want to watch the [Patching Snap Camera on Mac OS](https://www.youtube.com/watch?v=lJhL7bA7GGA) video and make sure to repeat each step.

**Comment by Droppe1** [comment]
Actually, I had tried several times following step by step, 
but apparently the MAC OS patch do not work: the app do not open (I'd gave the permission to open app form everywhere)
I had tried the MAC OS | NCS  and the app open but the patch doesn't works ...

**Comment by ptrumpis** [comment]
The regular mac OS patch should work. I would suggest re-installing snap camera, patching and rebooting your system afterwards.

**Comment by Droppe1** [comment]
I tried several time, I think the issue on Ventura can be the signature remover https://reverseengineering.stackexchange.com/questions/13622/remove-code-signature-from-a-mac-binary

What do you think?

I'm trying to to find out a workaround.  I let you know if you can find something.

Cheers
