### ISSUE TITLE
The server doesn't start

### ISSUE THREAD

**Issue by bitnosis** [ptrumpis/snap-camera-server#61]
stoic_yonath                       | file:///usr/src/app/src/utils/importer.js:12
stoic_yonath                       | const mediaDir = process.env.MEDIA_DIR.replace(/^\/+/, '');
stoic_yonath                       |                                        ^
stoic_yonath                       | 
stoic_yonath                       | TypeError: Cannot read properties of undefined (reading 'replace')
stoic_yonath                       |     at file:///usr/src/app/src/utils/importer.js:12:40

I get the following error when clicking the Play button on docker :(

**Comment by bitnosis** [comment]
Looks like I was able to get past that by doing `docker compose --env_file .env up`.   

But now I get this error...
```
2023/09/06 21:09:14 [emerg] 1#1: cannot load certificate key "/etc/ssl/private/studio-app.snapchat.com.key": BIO_new_file() failed (SSL: error:80000001:system library::Operation not permitted:calling fopen(/etc/ssl/private/studio-app.snapchat.com.key, r) error:10080002:BIO routines::system lib)
snap-camera-server-311-webproxy-1  | nginx: [emerg] cannot load certificate key "/etc/ssl/private/studio-app.snapchat.com.key": BIO_new_file() failed (SSL: error:80000001:system library::Operation not permitted:calling fopen(/etc/ssl/private/studio-app.snapchat.com.key, r) error:10080002:BIO routines::system lib)
```

**Comment by ptrumpis** [comment]
You didn't fill out the issue template.
I can't help if I don't even know your operating system.

Open another ticket with the information provided if you want assistance.
