### ISSUE TITLE
Face Detection Lenses Only Buffer

### ISSUE THREAD

**Issue by MiX74P3** [ptrumpis/snap-camera-server#72]
**System Information (please complete the following information):**
 - OS: Windows
 - Snap Camera Version: 1.21
 - Signature Patch applied: yes

**Please follow these steps to provide detailed information**
1. Open Snap Camera
2. Select all Lenses that are not working in your app
3. Copy and attach the Snap Camera log file to this ticket

   [Log.txt](https://github.com/ptrumpis/snap-camera-server/files/12863006/Log.txt)

**Please also provide the lens share link**
https://snapchat.com/unlock/?type=SNAPCODE&uuid=b424e87885e74950a88b1f940a648c01&metadata=01
https://snapchat.com/unlock/?type=SNAPCODE&uuid=cdbed3887df54fd482b8176f1501e8be&metadata=01
https://snapchat.com/unlock/?type=SNAPCODE&uuid=4adee3cdf847467f8af71b4df7e20d57&metadata=01
https://snapchat.com/unlock/?type=SNAPCODE&uuid=a0daca382fd94cfebe03bc9cf4e7141e&metadata=01

Every lens that detect face like these just buffers continuously. Not just theses 4 but every single one that is built like these. Or am I doing something wrong? All other lenses are working great.

**Comment by ptrumpis** [comment]
There are some additional assets missing.

You can also check the the main disussion for working/non-working lenses: [List of incompatible Lenses](https://github.com/ptrumpis/snap-camera-server/discussions/8)

**Comment by MiX74P3** [comment]
so no way to get them working as of now?

**Comment by ptrumpis** [comment]
There is a work arround, but it requires to [manually unpack, edit and re-pack](https://github.com/ptrumpis/snap-camera-server/discussions/8#discussioncomment-6514674) the lens files.
