### ISSUE TITLE
Error with webproxy-1 in Docker.

### ISSUE THREAD

**Issue by MiX74P3** [ptrumpis/snap-camera-server#79]
Please make sure the **Wiki** and **Discussions** section does not solve your problem:
- https://github.com/ptrumpis/snap-camera-server/wiki
- https://github.com/ptrumpis/snap-camera-server/discussions

If you are having technical difficulties please provide the following information:
**System (please complete the following information):**
 - OS:Windows
 - Server Version: Not sure Server Version. Most likely Newest
 - Snap Camera Version: 1.21
 - Signature Patch applied: yes
 I came hoe from work today and docker is not running the webproxy-1. it runs and exits. I have been using this over a month now with no issues. What do I need to do to fix this?

https://i.imgur.com/A1Annbe.png

Error: (HTTP code 400) unexpected - failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/d/Desktop/snap-camera-server-main/nginx/default.conf.template" to rootfs at "/etc/nginx/templates/default.conf.template": mount /run/desktop/mnt/host/d/Desktop/snap-camera-server-main/nginx/default.conf.template:/etc/nginx/templates/default.conf.template (via /proc/self/fd/9), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by ptrumpis** [comment]
Did you change any files?
Make sure the file [nginx/default.conf.template](https://github.com/ptrumpis/snap-camera-server/blob/main/nginx/default.conf.template) exists.

You can [re-download](https://github.com/ptrumpis/snap-camera-server/releases) original files and overwrite your existing files any time.

**Comment by MiX74P3** [comment]
https://i.imgur.com/YhbPuXq.png

**Comment by MiX74P3** [comment]
server {
    listen *:${HTTP_PORT} default_server;
    listen *:443 default_server ssl;

    server_name studio-app.snapchat.com;

    ssl_certificate /etc/ssl/certs/studio-app.snapchat.com.crt;
    ssl_certificate_key /etc/ssl/private/studio-app.snapchat.com.key;

    root ${WWW_ROOT};

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    client_max_body_size 256M;

    autoindex on;
    autoindex_exact_size off;
    autoindex_format html;
    autoindex_localtime on;

    # because my eyes hurt working at night
    add_before_body /theme/header.html;
    add_after_body /theme/footer.html;

    location /theme/ {
        root /etc/nginx;
    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
        return 204;
    }

    # redirect all API calls
    location /vc/ {
        add_header        'Access-Control-Allow-Origin' '*' always;
        proxy_pass         http://webapp:${WEBAPP_PORT}/vc/;
        proxy_redirect     off;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Forwarded-Host $server_name;
    }

    # New Snapcode URL Support
    # http://localhost/web/deeplink/snapcode/?data=UUID&type=PNG
    location /web/deeplink/snapcode {
        if ($arg_type) {
             set $fileext "$arg_type";
        }
        if ($arg_type = "") {
             set $fileext "png";
        }
        if ($arg_data) {
            rewrite ^(.*)$ /web/deeplink/snapcode/$arg_data.$fileext break;
        }
    }
}

**Comment by MiX74P3** [comment]
it had been deleted but i restored it back. but still not working

**Comment by MiX74P3** [comment]
Error: (HTTP code 400) unexpected - failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/d/Desktop/snap-camera-server-main/ssl/studio-app.snapchat.com.crt" to rootfs at "/etc/ssl/certs/studio-app.snapchat.com.crt": mount /run/desktop/mnt/host/d/Desktop/snap-camera-server-main/ssl/studio-app.snapchat.com.crt:/etc/ssl/certs/studio-app.snapchat.com.crt (via /proc/self/fd/9), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by MiX74P3** [comment]
i replaced with completely new download files from https://github.com/ptrumpis/snap-camera-server/releases and its still not running webproxy-1

**Comment by MiX74P3** [comment]
i was able to fix it. ty much
