### ISSUE TITLE
I found a couple of lenses that it does not work with.

### ISSUE THREAD

**Issue by MikeyWetzel** [ptrumpis/snap-camera-server#88]
**System Information (please complete the following information):**
 - OS: Windows 11 Pro
 - Snap Camera Version: 1.21
 - Signature Patch applied: yes, v3

Note:  (Windows): %USERPROFILE%\AppData\Local\Snap\Snap Camera\Log.txt is EMPTY!

Links to lenses not working:
https://www.snapchat.com/lens/491b02605519412cad4f8d3b033bb66d)
https://www.snapchat.com/lens/ce55d7f2d6774981a729fa3330e68a93

In trying to get the logs to you, now I can't get any filters to work. Like the server stopped. (But it is running in docker. Might be reboot time.)

**Comment by ptrumpis** [comment]
Thanks for reporting, you can find an updated list with non working lenses and possible workarounds.

[List of incompatible Lenses](https://github.com/ptrumpis/snap-camera-server/discussions/8)
