### ISSUE TITLE
lens studio question

### ISSUE THREAD

**Issue by DamianArielLerner** [ptrumpis/snap-camera-server#9]
it's not about the server but i uploaded a snapchat lens but is not appearing in the lens page and snap camera, what is happening? lens studio says that is public
https://lens.snapchat.com/e3c2f7824b6e482285c2b58e30a08ec8?sender_web_id=9b5c4337-f382-4361-b0c9-efde83a34cd4&device_type=desktop&is_copy_url=true
thanks!

**Comment by ptrumpis** [comment]
Just paste the lens link into the search field.
Did you use server version 2.x ?

**Comment by DamianArielLerner** [comment]
I'm using the last version. Ok it worked to paste the link in the search field, but now if I'm using the lens in snap camera the webcam freezes.

**Comment by ptrumpis** [comment]
You need to have the signature patch applied if you want to use web lenses.

If your lens was created/published after January 25 it might not work, this project is about returning missing lenses that were in use before the Shutdown. It's not about maintaining Snap Camera.

**Comment by DamianArielLerner** [comment]
Sad. Is there a way that my lens after 25 can work in the app?

**Comment by ptrumpis** [comment]
Snap lenses not working after January 25th is a guess on my part and not a proven fact. I'm still trying to find out if that's really the case. Here are some non working examples: https://github.com/ptrumpis/snap-camera-server/discussions/8

You can use Snapchat on your smartphone and connect your smartphone to your computer. I've never done it myself but I've watched video tutorials and the result looked good.
Most streamers rely on Snap Camera's hot key feature to connect lenses to their bots/channelpoints.

But did you apply this patch? https://ptrumpis.github.io/snap-camera-signature-patch/

**Comment by ptrumpis** [comment]
> Sad. Is there a way that my lens after 25 can work in the app?

@DamianArielLerner I found out why they are not working and I know how to fix that 😎

Please add your none working lenses here:
[List of non working lenses](https://github.com/ptrumpis/snap-camera-server/discussions/8)

I'll work down the list from top to bottom and restore the Lenses

**Comment by ptrumpis** [comment]
@DamianArielLerner 
- https://github.com/ptrumpis/snap-camera-server/wiki/Updating-Snap-Camera-(Unofficial)
- https://github.com/ptrumpis/snap-camera-server/wiki/List-of-Assets

This will fix your problem

**Comment by DamianArielLerner** [comment]
Ok, in a few days I will taste it, you are amazing! I didn't think than you can upload an unofficial version to solve my problem
