### ISSUE TITLE
How to change GPU being used with this app?

### ISSUE THREAD

**Issue by sayyid5416** [ptrumpis/snap-camera-server#92]
I have two graphic cards on my system. One is integrated AMD graphic card which comes with ryzen 5 5600g, and second one is RTX 3060.

I WANT TO SET A SPECIFIC GRAPHIC CARD TO BE USED WITH THIS.

**Comment by ptrumpis** [comment]
The question has nothing to do with snap camera. It depends on the graphics card software settings. Check your driver settings or ask amd/nvidia support if you can't find the option.

**Comment by sayyid5416** [comment]
@ptrumpis There is option to change this in Windows 11 _(which NVIDIA also recommends)_ in `Settings > System > Display > Graphics`. All apps are working fine with this. **Snapcamera is the only app which is not working with this.** 

It doesn't matter which GPU I set for Snapcamera, It keep using dedicated gpu. That's why I think it is related to snapcamera.
