### ISSUE TITLE
Please support Linux version.

### ISSUE THREAD

**Issue by TaiTitans** [ptrumpis/snap-camera-server#94]
Please make sure the **Wiki** and **Discussions** section does not solve your problem:
- https://github.com/ptrumpis/snap-camera-server/wiki
- https://github.com/ptrumpis/snap-camera-server/discussions

If you are having technical difficulties please provide the following information:
**System (please complete the following information):**
 - OS: [e.g. Windows, Mac OS]
 - Server Version: [e.g. 2.0.6, , 3.0.0, 3.0.1, ...]
 - Snap Camera Version: [e.g. 1.19, 1.20, 1.21]
 - Signature Patch applied: [yes or no]

**Comment by ptrumpis** [comment]
Server runs on Windows, Mac or Linux.
Client application runs on Windows and Mac only.

If you want to run the client application with Linux you need to use KVM (virtual machine) and probably enable GPU passthrough.

**Comment by TaiTitans** [comment]
:< I dont want use KVM. I want use on Linux.
