### ISSUE TITLE
Lens Stops Working After 30 Minutes - Search Result Drop Out

### ISSUE THREAD

**Issue by jlfagan98** [ptrumpis/snap-camera-server#96]
Im using the lens pack which includes all of the newer & more recent lenses, and activating a lens it by searching the link within the program, it loads and works flawlessly for 30 minutes. After this it will suddenly drop out, losing the searcehd lens and deactivating the filter completely. The searched lens also disappears from the search results. I then need to clear the search bar and start from scratch. 

Why is SnapCam losing the lens exactly every 30 minutes? Is it pinging docker every 30 mins when no lens change is made?

I have tried activating and deactivating the lens and it does not reset the 30 minute timer. Only removing the lens link in the search window, re searching and reactivating will restart the process.

BEFORE
![Screenshot 2024-01-22 150215](https://github.com/ptrumpis/snap-camera-server/assets/142013417/0675ca13-ca23-438b-ad42-2e05e7ecd0be)

AFTER 30 MINS
![2sn](https://github.com/ptrumpis/snap-camera-server/assets/142013417/6abc9825-979d-45a7-9ef3-82c0d480c82f)

 - OS: [Win11]
 - Server Version: [3.1.1]
 - Snap Camera Version: [1.21]
 - Signature Patch applied: [yes]

**Comment by ptrumpis** [comment]
What do you mean by lens pack?
Are you using the original snap camera appilcation: [Download](https://github.com/ptrumpis/snap-camera-server/discussions/6)

I've never heard of such a problem before

**Comment by jlfagan98** [comment]
Apologies I meant the Asset pack for newer lenses. 
I have reinstalled everything from scratch and the issue has been resolved, likely because I had patched over an already patched version of Jaku's release of Snapcam rather than a vanilla file.
