### ISSUE TITLE
All Lens are not displayed

### ISSUE THREAD

**Issue by Lamadros** [ptrumpis/snap-camera-server#97]
**System Information (please complete the following information):**
 - OS: Mac OS ( Venture 13.4 (22F66) )
 - Macbook: 14 inc 2021, Apple M1 Pro.
 - Snap Camera Version: 1.21
 - Signature Patch applied: yes

**Please follow these steps to provide detailed information**
1. Open Snap Camera
2. Select all Lenses that are not working in your app
3. Copy and attach the Snap Camera log file to this ticket
   - (Mac OS): /Users/{YOUR_USER_NAME}/Library/Preferences/Snap/Snap Camera/Log.txt
   
[Log.txt](https://github.com/ptrumpis/snap-camera-server/files/14053623/Log.txt)

<img width="949" alt="image" src="https://github.com/ptrumpis/snap-camera-server/assets/16326544/27140266-130f-4de5-9d87-0494a863f7eb">

**Extra information:**
1. I do all these steps from this video -> https://www.youtube.com/watch?v=6ezl5hCqm5w&lc=Ugw98NJUzgbj2w3jSBZ4AaABAg.9zLfueTs8U09zMGnPJooB6
2. I also run errorfix.sh here the output of terminal:
```
Sashas-MacBook-Pro ~ % sh ~/Downloads/errorfix.sh 
Generating MD5 checksum of the Snap Camera binary file
/Users/sashazhgut/Downloads/errorfix.sh: line 22: 8dc456e29478a0cdfaedefac282958e7: value too great for base (error token is "8dc456e29478a0cdfaedefac282958e7")
/Users/sashazhgut/Downloads/errorfix.sh: line 24: 94218d95ced39db2f86f25ef2daa7384: value too great for base (error token is "94218d95ced39db2f86f25ef2daa7384")
Making the binary executable.
Removing the macOS code signing.
Removing extended file attributes.
Re-Signing the application.
You should be able to open Snap Camera now.
```

**Comment by ptrumpis** [comment]
I updated the errorfix.sh script, please download and run it again and share the output.
Make sure the docker server is running in the background.

**Comment by ptrumpis** [comment]
Hm it can't find the file `server.js`, is the file present in the server directory?
Did you edit any files?

**Comment by Lamadros** [comment]
`server.js` is presented:
<img width="1035" alt="image" src="https://github.com/ptrumpis/snap-camera-server/assets/16326544/9aef87ff-0859-4121-97cb-218d2db73c3c">



I modified only docker compose file ( since I have M1 chip):

<img width="946" alt="image" src="https://github.com/ptrumpis/snap-camera-server/assets/16326544/cee7db05-678b-4369-9e3a-3ebb2a5b7fce">




I can remove everything and re-run from scratch or move snap-server folder move from application folder to f.e. Downloads.

**Comment by ptrumpis** [comment]
I've never seen that error before.

Did you whitelist the server folder in your settings?
[Video Tutorial](https://youtu.be/b2ILHJaD1T4?feature=shared&t=432)

**Comment by Lamadros** [comment]
yeap
<img width="1093" alt="image" src="https://github.com/ptrumpis/snap-camera-server/assets/16326544/6b2257aa-6a65-48f7-91f7-692f0d6ad836">

**Comment by ptrumpis** [comment]
Try to delete the webapp (also delete under "images" in left menu) and restart server

![todo](https://github.com/ptrumpis/snap-camera-server/assets/116500225/bdd78f0c-3f3a-4029-bba7-99e0ef67c955)

**Comment by Lamadros** [comment]
when I do this, I got error that I can not restart application:
`Cannot stop Docker Compose application. Reason: compose [stop] exit status 1. could not find webapp: not found` the same situation when I try to start snap-camera server. 

So, what I do:
I remove server from application and then put again after that I update to latest version of the docker. Also I add chmod 777 to ssl folder. And after that webapp started. IDK which step gave the result...

for now in terminal I see these errors with connection:
<img width="1470" alt="image" src="https://github.com/ptrumpis/snap-camera-server/assets/16326544/8c73131c-e5b7-47d0-bd7f-63fa3db44668">

**Comment by ptrumpis** [comment]
> should I remove all images and containers and re-run docker compose up?

If there are still problems, you should remove everything including the volumes.
This command should undo and reset everything if you don't want to do it manually:

```
docker-compose down --rmi all -v --remove-orphans
```

**Comment by Lamadros** [comment]
Hello, 
So, I run this command and it's doesn't work. What I do:
 - I restarted docker
 - increase version of MySQL 
 
 After these steps I was able to run everything. 
 
 
 TY for your help, this issue we can close. 
 
 
 p.s. Maybe you know how can I fix problem that snap camera video doesn't displayed in Meets, Zoom etc? 
 
<img width="807" alt="image" src="https://github.com/ptrumpis/snap-camera-server/assets/16326544/d7dcf607-4f91-4058-bf14-ecc80ddb5b65">

**Comment by ptrumpis** [comment]
> p.s. Maybe you know how can I fix problem that snap camera video doesn't displayed in Meets, Zoom etc?

For macOS 14 check out:
https://github.com/ptrumpis/snap-camera-server/discussions/76

For other macOS versions continue here:
https://github.com/ptrumpis/snap-camera-server/discussions/78
